#!/bin/bash 
#SBATCH --job-name=train_minilm_udea
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=msteams:marquez
#SBATCH --ntasks=4 
#SBATCH --cpus-per-task=2
#SBATCH --time=48:00:00 
#SBATCH --output=logs/training_minilm_%j.log 
#SBATCH --partition=RTX
#SBATCH --gres=gpu:1
#SBATCH --mem=16G

#gres=gpu:1 if using RTX partition
#--gpus=1g.20gb:1 if using A100 partition

source .venv/bin/activate 

python -BO train.py --model_name all-MiniLM-L12-v2